{load href="/static/css/model.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/js/index/model.js" /}
{load href="/static/js/index/event/add_game.js" /}
{load href="/static/css/index/event/index.css" /}
<div class="add">
    <a href="<?php echo !empty($user)?'javascript:;':'/user/login';?>" id="<?php echo isset($user)?'joinGame':'';?> " event-status="<?php echo $event['status'];?>">加入比赛</a><br>
</div>
<div class="event-main">
    <div class="event">
        <div class="event-text">
            <li><span><?php echo $event['name'];?></span></li>
            <li><span><?php echo $event['address'];?></span></li>
            <li><span><?php echo $types[$event['type']];?></span></li>
            <li><span>举办方：<?php echo $createUser['name'];?></span></li>
            <li><span>开始：<?php echo $event['start_time'];?></span></li>
            <li><span>结束：<?php echo $event['end_time'];?></span></li>
        </div>
        <div class="event-logo">
            <img src="<?php echo $event['posters'];?>" width="390px">
        </div>
        <div class="event-desc">
            <p>简介：</p>
            <p><?php echo $event['describe'];?></p>
        </div>
    </div>
    <div class="event-joins">
        <span>参赛队伍</span>
        <?php if(!empty($joinClubs)):?>
        <?php foreach ($joinClubs as $key=>$joinClub):?>
            <li ><?php echo $joinClub;?></li>
        <?php endforeach;?>
        <?php endif;?>
    </div>
</div>
<div class="schedule">
    <div class="schedule-title">赛程表</div>
    <table>
        <thead>
        <tr>
            <?php if($event['type']==0):?>
                <th>小组</th>
            <?php endif;?>
            <th>比赛时间</th>
            <th>主队</th>
            <th>客队</th>
            <th>比分</th>
            <th>操作</th>
        </tr>
        </thead>
        <?php if(!empty($schedules)):?>
        <?php $group=range('A','Z');?>
            <?php foreach ($schedules as $key=>$schedule):?>
                <thead>
                <tr>
                    <?php if($event['type']==0):?>
                        <td><?php echo is_int($schedule['group'])?$group[$schedule['group']]:$schedule['group'];?></td>
                    <?php endif;?>
                    <td><?php echo date('Y-m-d H:i:s',$schedule['game_time']);?></td>
                    <td><?php echo idOfFiler('club',['Id'=>$schedule['home_team']],'name')?></td>
                    <td><?php echo idOfFiler('club',['Id'=>$schedule['visiting_team']],'name')?></td>
                    <td><?php echo $schedule['acting']!=0?$schedule['home_score'].' : '.$schedule['visiting_score']:'未开赛';?></td>
                    <td>
                        <?php if($schedule['over']==1):?>
                            <a href="/index/game/index?id=<?php echo $schedule['Id'];?>">查看详情</a>
<!--                        --><?php //else:?>
<!--                            <a href="/user/game?id=--><?php //echo $schedule['Id'];?><!--">进入比赛</a>-->
                        <?php elseif($schedule['acting']!=0 or $schedule['acting']!=3):?>
                            <a href="/index/game/index?id=<?php echo $schedule['Id'];?>">查看直播</a>
                        <?php endif;?>
                    </td>
                </tr>
                </thead>
            <?php endforeach;?>
        <?php endif;?>
    </table>
</div>

<div class="modal fade" id="modelAddGame">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">加入比赛</h4>
            </div>
            <div class="error" style="display: none;color: red">
                <span class="tc_error"></span>
            </div>
            <div class="modal-body">
                <form class="" id="joinGameForm">
                    <input type="hidden" name="eventId" id="eventId" value="<?php echo $event['Id'];?>">
                    <div>
                        <textarea  name="code" id="code" ></textarea>
                    </div>
                    <div class="chooseClub">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <input type="button"  id="addGameButton" value="加入" >
                <input type="button"  id="applyGameButton" value="申请" >
            </div>
        </div>
    </div>
</div>
