<?php
/**
 * Created by PhpStorm.
 * User: Viter
 * Date: 2018/2/25
 * Time: 21:30
 */
namespace app\admin\controller;
use base\Base;
use think\Db;
use think\Session;
class Index extends Base{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->engine->layout(false);//不使用模板
    }

    //登陆主页
    public function index(){
        return $this->fetch('index');
    }
    //登陆
    public function login(){
        $request = $this->request;
        $userName = $request->param('userName','','string');
        $password = $request->param('password','','string');
        $code = strtolower($request->param('code','','string'));
        $sission = new Session();
        $virefyCode = $sission->get('adminLogin_virefy_code');
        if(strcasecmp($virefyCode,$code)!==0){
            return $this->returnJson('验证码错误');
        }
        $admin = Db::name('admin')->where(array('name'=>$userName))->find();
        if (empty($admin)){
            $admin = Db::name('admin')->where(array('mobile'=>$userName))->find();
        }
        if(empty($admin)){
            return $this->returnJson('账号不存在,请重新确认');
        }
        $password = sha1($password.$admin['name']);
        if(strcmp($password,$admin['password'])!==0){
            return $this->returnJson('密码不正确');
        }
        $sission->push('admin_user',$admin);
        $res = Db::name('admin')->update(array('Id'=>$admin['Id'],'login_time'=>time()));
        return $this->returnJson('登陆成功',true,1);
    }

}