
    <!-- 修改密码 start -->
        <div class="modal fade" id="alterPassword">
            <div class="modal-dialog custom-modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">修改密码</h4>
                    </div>
                    <div class="modal-body dealbag-modal-body">
                        <form class="form-horizontal form-groups-bordered form-static" id="passwordForm">
                            <div class="form-group" id="originalPassword">
                                <label for="alterTitle" class="col-md-4 control-label">原始密码</label>
                                <div class="col-md-5">
                                    <input type="password" name="oldpwd" id="oldpwd" class="form-control" placeholder="请输入原始密码">
                                </div>
                            </div>
                            <div class="form-group" id="newPassword">
                                <label for="alterTitle" class="col-md-4 control-label">新密码</label>
                                <div class="col-md-5">
                                    <input type="password" name="newpwd" id="newpwd" class="form-control" placeholder="请输入新密码">
                                </div>
                            </div>
                            <div class="form-group" id="renewPassword">
                                <label for="alterClearno" class="col-md-4 control-label">确认密码</label>
                                <div class="col-md-5">
                                    <input type="password" name="renewpwd" id="renewpwd" class="form-control" placeholder="请输入新密码">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <div class="row">
                            <div class="col-md-7">
                                <input type="button" name="savePassword" id="savePassword" value="保存" class="btn btn-default">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- 用户详情 end -->
        <script src="/adminAssets/js/gsap/main-gsap.js" id="script-resource-1"></script>
        <script src="/adminAssets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js" id="script-resource-2"></script>
        <script src="/adminAssets/js/bootstrap.js" id="script-resource-3"></script>
        <script src="/adminAssets/js/joinable.js" id="script-resource-4"></script>
        <script src="/adminAssets/js/resizeable.js" id="script-resource-5"></script>
        <script src="/adminAssets/js/neon-api.js" id="script-resource-6"></script>
        <script src="/adminAssets/js/neon-custom.js" id="script-resource-10"></script>
        <script src="/adminAssets/plugins/datetimepicker/bootstrap-datetimepicker.min.js"></script>
        <script src="/adminAssets/js/daterangepicker/daterangepicker.js"></script>
        <script src="/adminAssets/js/bootstrap-datepicker.js"></script>
        <script src="/adminAssets/js/bootstrap-colorpicker.min.js"></script>
        <script src="/adminAssets/js/bootstrap-timepicker.min.js"></script>
        <script src="/adminAssets/js/daterangepicker/moment.min.js"></script>
        <script src="/adminAssets/script/verify-defined.js"></script>
        <script src="/adminAssets/script/records-per-page.js"></script>
        <script src="/adminAssets/script/admin-user.js"></script>
        <script src="/adminAssets/js/daterangepicker/daterangepicker.js"></script>
    </body>
</html>