<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="renderer" content="webkit"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Neon Admin Panel" />
        <title><?php if (isset($title) && $title): ?><?php echo $title; ?><?php else: ?><?php echo 'BasketballClub后台管理系统'; ?><?php endif; ?></title>
        <link rel="stylesheet" href="/adminAssets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css"  id="style-resource-1">
        <link rel="stylesheet" href="/adminAssets/css/font-icons/entypo/css/entypo.css"  id="style-resource-2">
        <link rel="stylesheet" href="/adminAssets/css/bootstrap.min.css"  id="style-resource-4">
        <link rel="stylesheet" href="/adminAssets/css/neon-core.min.css"  id="style-resource-5">
        <link rel="stylesheet" href="/adminAssets/css/neon-theme.min.css"  id="style-resource-6">
        <link rel="stylesheet" href="/adminAssets/css/neon-forms.min.css"  id="style-resource-7">
        <link rel="stylesheet" href="/adminAssets/css/bootstrapValidator.css"  id="style-resource-8">
        <link rel="stylesheet" href="/adminAssets/css/font-icons/font-awesome/css/font-awesome.min.css"  id="style-resource-9">
        <link rel="stylesheet" type="text/css" href="/adminAssets/plugins/datetimepicker/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" type="text/css" href="/adminAssets/js/daterangepicker/daterangepicker-bs3.css" />
        <link rel="stylesheet" type="text/css" href="/adminAssets/style/custom/general-layout.css" />
        <link rel="stylesheet" type="text/css" href="adminAssets/style/custom/table-layout.css" />

        <script src="/adminAssets/js/jquery-1.11.0.min.js"></script>
        <script src="/adminAssets/js/bootstrapValidator.js"></script>
        <script type="text/javascript" charset="utf-8" src="/adminAssets/lib/ueditor/ueditor.config.js"></script>
        <script type="text/javascript" charset="utf-8" src="/adminAssets/lib/ueditor/ueditor.all.min.js"></script>
<!--         <script src="/assets/js/custom.js"></script>
        <script src="/assets/js/demo.js"></script>
 -->        <!--[if lt IE 9]><script src="http://themes.laborator.co/neon/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- TS1395716029: Neon - Responsive Admin Template created by Laborator -->
    </head>
    <body class="page-body" data-url="/">
        <div class="page-container page-width">
