{load href="/adminAssets/style/custom/neno/sidebar.css" /}
<div class="sidebar-menu sidebar-width">
  <header class="logo-env">
    <div class="logo custom-logo-left">
      <a href="/admin/management"><img width="140" src="/static/image/logo.png" alt="" /></a>
    </div>
    <div class="sidebar-collapse custom-collapse-top">
      <a href="/admin/management" class="sidebar-collapse-icon with-animation"><i class="entypo-menu"></i></a>
    </div>
    <div class="sidebar-mobile-menu visible-xs">
      <a href="/admin/management" class="with-animation"><i class="entypo-menu"></i></a>
    </div>
  </header>
    <ul id="main-menu" class="">
        <li class="root-level">
            <a href="/admin/management/"><i class="entypo-users"></i><span>管理员列表</span></a>
        </li>
        <li class="root-level">
            <a href="/admin/event/"><i class="entypo-air"></i><span>赛事审核</span></a>
        </li>
        <li class="root-level">
            <a href="/admin/user/"><i class="entypo-users"></i><span>用户列表</span></a>
        </li>
    </ul>
</div>



