<div class="row">
    <div class="col-md-6 col-sm-8 clearfix">
        <ul class="user-info pull-left pull-none-xsm">
            <li class="profile-info dropdown">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="/adminAssets/images/avatar.jpg" alt="" class="img-circle" width="44">
                    <?php echo isset($admin['name'])?$admin['name']:'';?>
                </a>
                <ul class="dropdown-menu">
                        <li class="caret"></li>
                        <li>
                            <a href="javascript:;" class="passwordmodal">
                                <i class="entypo-lock"></i>
                                修改密码
                            </a>
                        </li>
                        <li>
                            <a href="/admin/logout/">
                                <i class="entypo-logout"></i>
                                退出
                            </a>
                        </li>
                    </ul>
            </li>
        </ul>
    </div>
    <div class="col-md-6 col-sm-4 clearfix hidden-xs">
        <ul class="list-inline links-list pull-right">
            <li>
                <a href="/admin/logout/">
                    用户退出 <i class="entypo-logout right"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
<hr>



