{load href="/static/js/jq.js" /}
{load href="/static/js/admin/mangement/index.js" /}
{load href="/adminStatic/style/custom/table-layout.css" /}

<ol class="breadcrumb bc-3">
    <li>
        <a href="/admin/management"><i class="entypo-home"></i>首页</a>
    </li>
    <li class="active">
        <strong>管理员列表</strong>
    </li>
</ol>

<h2>管理员列表</h2>

<div class="dataTables_wrapper form-inline">
    <div class="row screen-sm">
        <div class="col-md-12 col-left">
            <div class="col-md-10" >
                <form action="" method="get" class="form-inline">
                    <div class="form-group">
                        <i class="entypo-search"></i>
                    </div>
                    <div class="form-group">
                        <input type="text" name="name" value="<?php echo empty($name)?'':$name;?>" placeholder="请输入管理员名称" class="form-control">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" id="search">查询</button>
                    </div>
                </form>
            </div>
            <div class="col-md-2" ><a href="javascript:;" class="btn btn-green" id="addAdmin">添加</a></div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-striped custom-table-font-size">
        <thead class="th-color">
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>联系方式</th>
        </tr>
        </thead>
        <tbody class="td-color" id="dataTable">
        <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$value):?>
                <tr>
                    <td><?php echo $value['Id'];?></td>
                    <td><?php echo $value['name'];?></td>
                    <td><?php echo $value['mobile'];?></td>
                </tr>
            <?php endforeach;?>
        <?php else:?>
            <td colspan="17"><center>没有找到管理员</center></td>
        <?php endif;?>
        </tbody>
    </table>
</div>
{include file="../application/index/view/public/pager.phtml"/}
</div>

<!-- 添加 显示信息 start -->
<div class="modal fade" id="moadladdAdmin">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">管理员添加</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal form-groups-bordered form-static" id="addClubForm">
                    <div class="form-group">
                        <label for="name" class="control-label col-md-2">用户名</label>
                        <div class="col-md-4">
                            <input type="text" name="name" id="addname" class="form-control" >
                        </div>
                    </div><div class="form-group">
                        <label for="mobile" class="control-label col-md-2">手机</label>
                        <div class="col-md-4">
                            <input type="text" name="mobile" id="addmobile" class="form-control" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="control-label col-md-2">密码</label>
                        <div class="col-md-4">
                            <input type="password" name="password" id="addpassword" class="form-control" >
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <input type="button" value="确认" class="btn btn-green addAdminButton" data-id="">
            </div>
        </div>
    </div>
</div>
<!-- 添加 显示信息 end -->