{load href="/static/css/model.css" /}
{load href="/static/css/index/clubs.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/js/index/model.js" /}
{load href="/static/js/index/index/clubs.js" /}
{load href="/static/js/index/area.js" /}

<div class="main">
    <div class="add">
        <a href="<?php echo !empty($user)?'javascript:;':'/user/login';?>" id="<?php echo isset($user)?'addClub':'';?>">创建球队</a><br>
    </div>
</div>
        <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$club):?>
                <?php if($key % 2==0):?>
                    <div class="club-list">
                    <?php if( $key == count($pager['data'])-1):?>
                        <div class="club-list-c">
                    <?php endif;?>
                            <div class="club-list-l">
                <?php else:?>
                    <div class="club-list-r">
                <?php endif;?>
                        <div class="club-list-img"><img src="<?php echo empty($club['mark'])?'':$club['mark'];?>"><span class="club-title"><?php echo $club['name'];?></span></div>
                   <div  class="club-list-ul" role="club" data-captain="<?php echo $club['captain'];?>">
                        <ul>
                            <li><strong>队长：</strong><span class="captainName"></span></li>
                            <li><strong><?php echo $club['area'];?></strong></li>
                            <li>
                                <?php $players = json_decode($club['players'],true);?>
                                <span class="grey"><?php echo count($players);?></span><strong>人</strong>
                            </li>
                        </ul>
                   </div>
                    <div class="into-right">
                        <?php if(!empty($user) and isset($players[$user['Id']])):?>
                            <a href="/user/club?id=<?php echo $club['Id'];?>">进入球队</a>
                        <?php else:?>
                            <a href="<?php echo !empty($user)?'javascript:;':'/user/login';?>" class="joinClub" data-id="<?php echo $club['Id'];?>">加入球队</a>
                        <?php endif;?>
                    </div>
                </div>
                <?php if( $key == count($pager['data'])-1):?>
                      </div><!-- list-c结束-->
                <?php endif;?>
                <?php if($key % 2==1 or $key==count($pager['data'])-1 ):?>
                    </div><!-- list结束-->
                <?php endif;?>
            <?php endforeach;?>
            {include file="../application/index/view/public/pager.phtml"/}
        <?php else:?>
            <div class="nothing-clubs">
                <span>没有找到球队</span>
            </div>
        <?php endif;?>
<!--</div><!-- main结束-->


<div class="modal fade" id="modelAddClub">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">创建球队</h4>
            </div>
            <div class="error" style="display: none;color: red">
                <span class="tc_error"></span>
            </div>
            <div class="modal-body">
                <form class="form-horizontal form-groups-bordered form-static" id="fauditingForm">
                    <label class="am-color" for="name">赛事名称：</label>
                    <input type="text" placeholder="请输入队伍名称" name="name" id="name">
                    <br />
                    <label class="am-color" for="areas">地区：</label>
                    <select  id="province" >
                        <option value="0">选择省区</option>
                        <?php foreach ($provinces as $key=>$value):?>
                            <option value="<?php echo $key;?>" ><?php echo $value;?></option>
                        <?php endforeach;?>
                    </select>
                    <select  id="city" >
                        <option value="0">选择市区</option>
                    </select>
                    <select  id="area" >
                        <option value="0">选择县区</option>
                    </select>
                    <br />
                    <label class="am-color" for="code">邀请码：</label>
                    <input type="text" placeholder="设置邀请码" name="code" id="code">
                    <br />
                    <label class="am-color" for="name">队伍标志：</label>
                    <input type="file" name="clubMark"  id="clubMark">
                    <input type="hidden" id="mark" name="mark" value="">
                    <br/>
                    <img src="" width="100" id="markImg"><br />
                </form>
            </div>
            <div class="modal-footer">
                <input type="button"  id="addClubButton" value="创建" >
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modelJoinClub">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">加入球队</h4>
            </div>
            <div class="error" style="display: none;color: red">
                <span class="tc_error"></span>
            </div>
            <div class="modal-body">
                <form class="form-horizontal form-groups-bordered form-static" id="joinClubForm">
                    <textarea placeholder="输入邀请码或理由" name="modal_string" id="modal_string"></textarea>
                </form>
            </div>
            <div class="modal-footer">
                <input type="button"  id="joinClubButton" value="加入" >
                <input type="button"  id="applyJoinButton" value="申请加入" >
            </div>
        </div>
    </div>
</div>

