{load href="/static/css/index/event.css"}
{load href="/static/js/jq.js"}
{load href="/static/js/index/index/event.js"}
<div class="event-seacher">
<!--    <div class="seacher-logo"><img src="/static/image/logo.png" height="70px"></div>-->
    <div class="seacher-logo">
        <div class="add">
            <a href="<?php echo !empty($user)?'/user/event/add':'/user/login';?>" id="<?php echo isset($user)?'addClub':'';?>">创建赛事</a><br>
        </div>
    </div>
    <div class="seacher-select">
        <ul>
            <li>
                <select id="areaSearch">
                    <option value="" <?php echo empty($myarea)?'selected':'';?>>地区</option>
                    <?php foreach ($areas as $key=>$value):?>
                        <option value="<?php echo $value?>" <?php echo $myarea == $value?'selected':'';?>><?php echo $value?></option>
                    <?php endforeach;?>
                </select>
            </li>
            <li>
                <select id="typeSearch">
                    <option value="-1" <?php echo $mytype == -1?'selected':'';?>>类型</option>
                    <?php foreach ($types as $key=>$value):?>
                        <option value="<?php echo $key?>" <?php echo $mytype == $key?'selected':'';?>><?php echo $value?></option>
                    <?php endforeach;?>
                </select>
            </li>
            <li>
                <select id="statusSearch">
                    <option value="-1" <?php echo $mystatus == -1?'selected':'';?>>状态</option>
                    <?php foreach ($status as $key=>$value):?>
                        <option value="<?php echo $key?>" <?php echo $mystatus == $key?'selected':'';?>><?php echo $value?></option>
                    <?php endforeach;?>
                </select>
            </li>
        </ul>
    </div>
    <div class="seacher-text">
        <div class="search-bk">
            <form action="" method="get">
                <input type="hidden" value="" id="formType" name="type">
                <input type="hidden" value="" id="formArea" name="area">
                <input type="hidden" value="" id="formStatus" name="status">
                <input type="text" name="name"  class="search-text-1">
            </form>
        </div>
    </div>
</div>
<?php if(!empty($pager['data'])):?>
    <?php foreach ($pager['data'] as $key =>$value):?>
        <?php if($key%2 ==0):?>
            <div class="event-list">
                <div class="list-image">
                    <img src="/static/image/event/kobe_left1.png" height="300px">
                </div>
                <div class="list-main">
                    <div class="list-main-top">
                        <img src="<?php echo empty($value['posters'])?'':$value['posters'];?>" >
                    </div>
                    <div class="list-main-silder-r">
                        <ul>
                            <li id="event-hot"><?php echo $showStatus[$value['status']];?><span class="join-num">参赛队伍<?php echo count(json_decode($value['join_clubs'],true));?></span></li>
                            <li><?php echo $value['name'];?></li>
                            <li><?php echo $types[$value['type']];?></li>
                            <li><?php echo $value['address'];?></li>
                        </ul>
                    </div>
                    <div class="list-main-bottom-l">
                        <img src="/static/image/small/time.png" width="32px"/><span><?php echo $value['start_time'].' 至 '.$value['end_time'];?></span>
                    </div>
                    <div class="list-main-bottom-r">
                        <a href="/index/event?id=<?php echo $value['Id'];?>">详情查看</a>
                    </div>
                </div>
                <div class="list-image">
                    <img src="/static/image/event/jordan_right1.png" height="300px" class="list-image-right">
                </div>
            </div>
        <?php else:?>
            <div class="event-list">
                <div class="list-image">
                    <img src="/static/image/event/jordan_left1.png" height="300px">
                </div>
                <div class="list-main">
                    <div class="list-main-top">
                        <img src="<?php echo empty($value['posters'])?'':$value['posters'];?>" >
                    </div>
                    <div class="list-main-silder-r">
                        <ul>
                            <li id="event-hot"><?php echo $showStatus[$value['status']];?><span class="join-num">参赛队伍<?php echo count(json_decode($value['join_clubs'],true));?></span></li>
                            <li><?php echo $value['name'];?></li>
                            <li><?php echo $types[$value['type']];?></li>
                            <li><?php echo $value['address'];?></li>
                        </ul>
                    </div>
                    <div class="list-main-bottom-l">
                        <img src="/static/image/small/time.png" width="32px"/><span><?php echo $value['start_time'].' 至 '.$value['end_time'];?></span>
                    </div>
                    <div class="list-main-bottom-r">
                        <a href="/index/event?id=<?php echo $value['Id'];?>">详情查看</a>
                    </div>
                </div>
                <div class="list-image">
                    <img src="/static/image/event/kobe_right1.png" height="300px" class="list-image-right">
                </div>
            </div>
        <?php endif;?>
    <?php endforeach;?>
    {include file="../application/index/view/public/pager.phtml"/}
<?php else:?>
<div class="nothing">
    <div class="nothing-top"><span>没有找到赛事</span></div>
    <div class="nothing-bottom">
        <a href="/user/event/add">前往添加</a>
    </div>
</div>
<?php endif;?>



