{load href="/static/js/jq.js" /}
{load href="/static/js/index/area.js" /}
{load href="/static/js/user/event/add.js" /}
{load href="/static/css/public.css"}
{load href="/static/css/user/addevent.css"}
<div class="add-event">
    <form name="addEventForm" id="addEventForm"  enctype="multipart/form-data" >
        <div class="k-div">
            <label class="am-color" for="name">赛事名称：</label>
            <input type="text" placeholder="请输入赛事名称" name="name" id="name">
        </div>
        <div class="k-div">
            <label class="am-color" for="text">赛制：</label>
            <select  id="type" name="type">
                <?php foreach ($types as $key=>$value):?>
                    <option value="<?php echo $key;?>" ><?php echo $value;?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div id="promotionDiv" style="display: none">
            <div class="k-div">
                <label  class="am-color" for="promotion">晋级队伍数:</label><input type="text" id="promotion" name="promotion">
            </div>
        </div>
        <div class="k-div">
            <label class="am-color" for="startTime">开始日期：</label>
            <i class="am-icon-calendar"></i>
            <input type="text"  placeholder="开始日期" name="startTime" id="startTime">
        </div>
        <div class="k-div">
            <label class="am-color" for="endTime">结束日期：</label>
            <i class="am-icon-calendar"></i>
            <input type="text"  placeholder="结束日期" name="endTime" id="endTime">
        </div>
        <div class="k-div">
            <label class="am-color" for="text">地区：</label>
            <input type="hidden" name="address" id="address">
            <select  id="province" >
                <option value="0">选择省区</option>
                <?php foreach ($provinces as $key=>$value):?>
                    <option value="<?php echo $key;?>" ><?php echo $value;?></option>
                <?php endforeach;?>
            </select>
            <select  id="city" >
                <option value="0">选择市区</option>
            </select>
            <select  id="area" >
                <option value="0">选择县区</option>
            </select>
        </div>
        <div class="k-div">
            <label >比赛海报:</label><input type="file" name="postersFile"  id="postersFile">
            <input type="hidden" id="posters" name="posters">
        </div>
        <div>
            <img src="" width="200" id="postersImg">
        </div>
        <input type="button" id="addEvent" value="添加赛事">
    </form>
</div>
