{load href="/static/js/jq.js" /}
{load href="/static/js/index/area.js" /}
{load href="/static/js/user/event/add.js" /}
<form name="addEventForm" id="addEventForm"  enctype="multipart/form-data" >
    <label class="am-color" for="name">赛事名称：</label>
    <input type="text" placeholder="请输入赛事名称" name="name" id="name">
    <br />
    <label class="am-color" for="text">赛制：</label>
    <select  id="type" name="type">
        <?php foreach ($types as $key=>$value):?>
            <option value="<?php echo $key;?>" ><?php echo $value;?></option>
        <?php endforeach;?>
    </select>
    <br />
    <label class="am-color" for="startTime">开始日期：</label>
    <i class="am-icon-calendar"></i>
    <input type="text"  placeholder="开始日期" name="startTime" id="startTime">
    <br />
    <label class="am-color" for="endTime">结束日期：</label>
    <i class="am-icon-calendar"></i>
    <input type="text"  placeholder="结束日期" name="endTime" id="endTime">
    <br />
    <label class="am-color" for="text">地区：</label>
    <input type="hidden" name="address" id="address">
    <select  id="province" >
        <option value="0">选择省区</option>
        <?php foreach ($provinces as $key=>$value):?>
            <option value="<?php echo $key;?>" ><?php echo $value;?></option>
        <?php endforeach;?>
    </select>
    <select  id="city" >
        <option value="0">选择市区</option>
    </select>
    <select  id="area" >
        <option value="0">选择县区</option>
    </select>
    <br />
    <label >比赛海报:</label><input type="file" name="postersFile"  id="postersFile">
    <input type="hidden" id="posters" name="posters">
    <br/>
    <img src="" width="200" id="postersImg"><br />
    <input type="button" id="addEvent" value="添加赛事">
</form>