{load href="/static/css/user/event/manage.css" /}
<div class="schedule">
    <div class="schedule-title">赛程表</div>
    <table>
        <thead>
        <tr>
            <?php if($event['type']==0):?>
                <th>小组</th>
            <?php endif;?>
            <th>比赛时间</th>
            <th>主队</th>
            <th>客队</th>
            <th>比分</th>
            <th>操作</th>
        </tr>
        </thead>
        <?php if(!empty($schedules)):?>
            <?php $group=range('A','Z');?>
            <?php foreach ($schedules as $key=>$schedule):?>
                <thead>
                <tr>
                    <?php if($event['type']==0):?>
                        <td><?php echo is_int($schedule['group'])?$group[$schedule['group']]:$schedule['group'];?></td>
                    <?php endif;?>
                    <td><?php echo date('Y-m-d H:i:s',$schedule['game_time']);?></td>
                    <td><?php echo idOfFiler('club',['Id'=>$schedule['home_team']])?></td>
                    <td><?php echo idOfFiler('club',['Id'=>$schedule['visiting_team']])?></td>
                    <!--                    <td><span class="homeTeam" data-id=" --><?php //echo $schedule['home_team'];?><!--"></span></td>-->
                    <!--                    <td><span class="visitingTeam" data-id=" --><?php //echo $schedule['visiting_team'];?><!--"></span></td>-->
                    <td><?php echo $schedule['over']==1?$schedule['home_score'].' : '.$schedule['visiting_score']:'未开赛';?></td>
                    <td>
                        <?php if($schedule['over']==1):?>
                            <a href="/index/game/index?id=<?php echo $schedule['Id'];?>">查看详情</a>
                        <?php else:?>
                            <a href="/user/game?id=<?php echo $schedule['Id'];?>">进入比赛</a>
                        <?php endif;?>
                    </td>
                </tr>
                </thead>
            <?php endforeach;?>
        <?php endif;?>
    </table>
</div>