<?php if(!empty($pager['data'])):?>
    <ul>
    <?php foreach ($pager['data'] as $key=>$data):?>
        <li>
            <div >
                名称：<?php echo $data['name'];?>
                地点：<?php echo $data['address'];?>
                赛制：<?php echo $types[$data['type']];?>
                时间：<?php echo $data['start_time'].'——'.$data['end_time'];?>
                <a href="/user/event/management?id=<?php echo $data['Id'];?>">进入管理</a>
            </div>
        </li>
    <?php endforeach;?>
    </ul>
<?php else:?>
    没有赛事
<?php endif;?>


