{load href="/static/css/model.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/js/index/model.js" /}
{load href="/static/js/user/club/index.js" /}
{load href="/static/css/user/club/index.css" /}
<div class="main-club">
    <div class="club-left">
        <div class="club-title">
            <div class="title-img">
                <img src="<?php echo empty($club['mark'])?'/static/image/logo.png':$club['mark'];?>" height="150px">
            </div>
            <div class="title-text">
                <li>
                    <?php echo $club['name'];?>
                </li>
                <li>
                    <?php echo $club['area'];?>
                </li>
                <li>
                    队长：
                    <a href="/user/club/player?id=<?php echo $club['captain'];?>" id="captainName" data-id="<?php echo $club['captain'];?>"></a>
                    <?php if($user['Id'] == $club['captain']):?>
                        <button id="changeCaptain">更换队长</button>
                    <?php endif;?>
                </li>
            </div>
        </div>
        <div class="club-log">
            <h3>球队日志</h3>
            <?php $log =  json_decode($club['log'],true);?>
            <?php foreach ($log as $value):?>
                <li><span style="color: grey"><?php echo $value;?></span></li>
            <?php endforeach;?>
        </div>
        <div class="club-apply">
            <h3>申请列表</h3>
            <table>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用户</th>
                    <th>申请理由</th>
                    <th>申请时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <?php if(!empty($applys)):?>
                    <?php foreach ($applys as $key=>$apply):?>
                        <thead>
                        <tr>
                            <td><?php echo $key+1;?></td>
                            <td><?php echo $apply['user_name'];?></td>
                            <td><?php echo $apply['reason'];?></td>
                            <td><?php echo date('Y-m-d H:i:s',$apply['time']);?></td>
                            <td>
                                <a href="javascript:;" class="pass" data-id="<?php echo $apply['Id'];?>">通过</a>
                                <a href="javascript:;" class="refuse" data-id="<?php echo $apply['Id'];?>">拒绝</a>
                            </td>
                        </tr>
                        </thead>
                    <?php endforeach;?>
                <?php endif;?>
            </table>
        </div>
    </div>
    <div class="club-right">
        <h3 style="color: honeydew;">队员列表</h3>
        <?php $nos = json_decode($club['players_no'],true);?>
        <?php foreach ($players as $userId=>$name):?>
            <li>
                <span style="color: grey"><?php echo $userId==$club['captain']?'队长：':'队员：';?></span>
                <a href="/user/club/player?id=<?php echo $userId;?>"><span><?php echo $name.' '.$nos[$userId].'号';?></span></a>
                <?php if($user['Id']==$club['captain'] and $userId!=$club['captain']):?>
                    <a href="javascript:;" class="delPlaers" data-id="<?php echo $userId;?>">踢出</a>
                <?php endif;?>
            </li>
        <?php endforeach;?>
    </div>

</div>

<div class="modal fade" id="modelChangeCaptain">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">更换队长</h4>
            </div>
            <div class="error" style="display: none;color: red">
                <span class="tc_error"></span>
            </div>
            <div class="modal-body">
                <form class="" id="changeCaptainForm">
                    <input type="hidden" id="clubId" value="<?php echo $club['Id'];?>">
                    <label >成员：</label>
                    <select id="playerId">
                        <?php foreach ($players as $key=>$player):?>
                            <option value="<?php echo $key?>"><?php echo $player;?></option>
                        <?php endforeach;?>
                    </select>
                </form>
            </div>
            <div class="modal-footer">
                <input type="button"  id="changeCaptainButton" value="更换" >
            </div>
        </div>
    </div>
</div>
