<?php if($user['Id'] == $club['captain']):?>
    <button id="changeCaptain">更换队长</button>
<?php endif;?>
<ul class="list">
    <li>
        <img src="<?php echo empty($club['mark'])?'/assets/i/logo/logogif.gif':$club['mark'];?>" width="100">
    </li>
    <li>
        队名：<?php echo $club['name'];?>
    </li>
    <li>
        队长：<a href="/user/club/player?id=<?php echo $club['captain'];?>"><?php echo $club['captain'];?></a>
    </li>
    <li>
        地区：<?php echo $club['area'];?>
    </li>
    <li>
        <div>
            球队日志：
            <?php $log =  json_decode($club['log'],true);?>
            <?php foreach ($log as $value):?>
                <ol><?php echo $value;?></ol>
            <?php endforeach;?>
        </div>
    </li>
    <li>
        队员列表：
        <?php foreach ($players as $userId=>$name):?>
        <a herf="/user/club/player?id=<?php echo $userId;?>"><ol><?php echo $name;?></ol></a>
        <?php endforeach;?>
    </li>
</ul>

{load href="/static/css/model.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/js/index/model.js" /}
{load href="/static/js/user/club/index.js" /}
<div class="modal fade" id="modelChangeCaptain">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">更换队长</h4>
            </div>
            <div id="error" style="display: none;color: red">
                <span class="tc_error"></span>
            </div>
            <div class="modal-body">
                <form class="" id="changeCaptainForm">
                    <input type="hidden" id="clubId" value="<?php echo $club['Id'];?>">
                    <label >成员：</label>
                    <select id="playerId">
                        <?php foreach ($players as $key=>$player):?>
                            <option value="<?php echo $key?>"><?php echo $player;?></option>
                        <?php endforeach;?>
                    </select>
                </form>
            </div>
            <div class="modal-footer">
                <input type="button"  id="changeCaptainButton" value="更换" >
            </div>
        </div>
    </div>
</div>
