<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><?php if (isset($title) && $title): ?><?php echo $title; ?><?php else: ?><?php echo '来战吧篮球';?><?php endif;?></title>
    {load href="/static/js/jq.js" /}
    {load href="/static/js/user/logout.js" /}
    {load href="/assets/css/amazeui.min.css" /}
    {load href="/assets/css/app.css" /}
    <style>
        .bg-black{
            background-color:#FF0000；
        }
    </style>
</head>
<body>
<div class=" am-container bg-black">
    <div class="am-topbar-brand app-logo">
        <a href="/">
            <img src="/assets/i/logo/logogif.gif" width="100">
        </a>
    </div>
    <div class="am-topbar-brand">
        <a href="/">
            <h2>来战吧篮球</h2>
        </a>
    </div>
    <div class="am-topbar-brand">
        <h2>让比赛变得更简单</h2>
    </div>
    <div class="am-topbar-brand">
        <h2>让数据变得更清晰</h2>
    </div>
    <div class="am-collapse am-topbar-collapse am-fr" id="doc-topbar-collapse">
        <ul class="am-nav am-nav-pills am-topbar-nav">
            <li ><a href="/index/index/event"> 赛事 </a></li>

            <li><a href="/index/index/clubs"> 球队  </a></li>
            <?php if(!empty($user)):?>
                <li><a href="/user"> 个人中心  </a></li>
                <li><a id="logout" href="javascript:;"> 登出  </a></li>
            <?php else:?>
                <li><a href="/user/login"> 登陆  </a></li>
                <li><a href="/user/regist"> 注册  </a></li>
            <?php endif;?>
        </ul>
    </div>
</div>