{load href="/static/js/jq.js" /}
{load href="/static/js/admin/user/index.js" /}
{load href="/adminStatic/style/custom/table-layout.css" /}

<ol class="breadcrumb bc-3">
    <li>
        <a href="/admin/management"><i class="entypo-home"></i>首页</a>
    </li>
    <li class="active">
        <strong>用户列表</strong>
    </li>
</ol>

<h2>用户列表</h2>

<div class="dataTables_wrapper form-inline">
    <div class="row screen-sm">
        <div class="col-md-12 col-left">
            <div class="col-md-10" >
                <form action="" method="get" class="form-inline">
                    <div class="form-group">
                        <i class="entypo-search"></i>
                    </div>
                    <div class="form-group">
                        <label class="control-label">状态</label>
                        <select class="form-control"  name="ban">
                            <option value="0" <?php echo $ban == 0? 'selected':''?>>正常用户</option>
                            <option value="1" <?php echo $ban == 1? 'selected':''?>>禁用用户</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" name="name" value="<?php echo empty($name)?'':$name;?>" placeholder="请输入用户姓名" class="form-control">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" id="search">查询</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-striped custom-table-font-size">
        <thead class="th-color">
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>身份证</th>
            <th>邮箱</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody class="td-color" id="dataTable">
        <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$value):?>
                <tr>
                    <td><?php echo $value['Id'];?></td>
                    <td><?php echo $value['name'];?></td>
                    <td><?php echo $value['idcard'];?></td>
                    <td><?php echo $value['email'];?></td>
                    <?php if($value['ban']==0):?>
                        <td>正常</td>
                        <td><a href="javascript:;" class="btn btn-red  btn-xs  ban"  data-id="<?php echo $value['Id'];?>" data-ban="1">禁用</a></td>
                    <?php else:?>
                        <td>禁用</td>
                        <td><a href="javascript:;" class="btn btn-green  btn-xs  ban"  data-id="<?php echo $value['Id'];?>" data-ban="0">解冻</a></td>
                    <?php endif;?>
                </tr>
            <?php endforeach;?>
        <?php else:?>
            <td colspan="17"><center>没有找到用户</center></td>
        <?php endif;?>
        </tbody>
    </table>
</div>
{include file="../application/index/view/public/pager.phtml"/}
</div>