{load href="/static/css/user/game/index.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/css/model.css" /}
{load href="/static/js/index/model.js" /}
{load href="/static/js/user/game/index.js" /}
<div class="header__info">
    <div class="header__team-name home-name"><?php echo $home['name'];?></div>
    <div class="header__team-score home-score"><?php echo $schedule['home_score'];?></div>
    <div class="header__time-box fl">
        <div class="header__picth"><?php echo $schedule['section']>4?'第'.($schedule['section']-4).'加时':'第'.$schedule['section'].'节'?></div>
        <div class="header__time"><?php echo (int)($schedule['second']/60);?>:<?php echo str_pad($schedule['second']%60,2,0);?></div>
    </div>
    <div class="header__team-name away-name"><?php echo $visiting['name'];?></div>
    <div class="header__team-score away-score"><?php echo $schedule['visiting_score'];?></div>
</div>
<div class="detail__box">
    <div class="detail__team fl">
        <div class="detail__team-name"><?php echo $home['name'];?></div>
        <form action="" method="get" class="lineup__form">
            <?php foreach ($homePlayers as $key=>$player):?>
                <div class="detail__team-item">
                    <?php if($playerStatus[$key]['is_playing']==1):?>
                        <input type="radio" name="homePlayer" value="<?php echo $key;?>" />
                    <?php endif;?>
                    <?php echo $player.' #'.$homeNo[$key];?>
                </div>
            <?php endforeach;?>
            <div class="detail__team-item">
                <input type="reset" class="detail__btn" value="重置">
            </div>
        </form>
    </div>
    <div class="detail__character">
        <?php foreach ($logs as $log):?>
            <p><?php echo $log;?></p>
        <?php endforeach;?>
    </div>
    <div class="detail__team fr">
        <div class="detail__team-name"><?php echo $visiting['name'];?></div>
        <form action="" method="get"  style="text-align: right;">
            <?php foreach ($visitingPlayers as $key=>$player):?>
                <div class="detail__team-item">
                    <?php echo $player.' #'.$visitingNo[$key];?>
                    <?php if($playerStatus[$key]['is_playing']==1):?>
                        <input type="radio" name="awayPlayer" value="<?php echo $key;?>" />
                    <?php endif;?>
                </div>
            <?php endforeach;?>
            <div class="detail__team-item">
                <input type="reset" class="detail__btn" value="重置">
            </div>
        </form>
    </div>
</div>
<div class="schedule_id" style="display:none;"><?php echo $schedule['Id'];?></div>
<div class="detail__btn-group">
    <select class="detail__select">
        <option value ="1">主队</option>
        <option value ="0">客队</option>
    </select>
    <span class="detail__btn">换人</span>
    <span class="detail__btn" id="j-returnBack">撤销</span>
    <span class="detail__btn start_to_stop" data-type="1">暂停</span>
    <span class="detail__btn start_to_stop" data-type="0" id="j-start"><?php echo $schedule['acting']==1?'死球停止':'开始';?></span>
    <?php if($schedule['second']==0):?>
        <span class="detail__btn"><?php echo ($schedule['section']+1)>4?'进入第'.($schedule['section']-3).'加时':'进入第'.($schedule['section']+1).'节'?></span>
    <?php endif;?>
    <?php if($schedule['second']==0 and $schedule['section']>=4):?>
        <span class="detail__btn">结束比赛</span>
    <?php endif;?>
    <br>
    <span class="detail__btn double_score" data-type="0">中投命中</span>
    <span class="detail__btn double_score" data-type="1">突破命中</span>
    <span class="detail__btn double_score" data-type="2">篮下命中</span>
    <span class="detail__btn double_score" data-type="3">补篮命中</span>
    <span class="detail__btn three_score" data-type="1">三分命中</span>
    <span class="detail__btn one_score" data-type="1">罚球命中</span>
    <br>
    <span class="detail__btn double_score" data-type="4">中投未中</span>
    <span class="detail__btn double_score" data-type="5">上篮未中</span>
    <span class="detail__btn double_score" data-type="6">篮下未中</span>
    <span class="detail__btn double_score" data-type="7">补篮未中</span>
    <span class="detail__btn three_score" data-type="0">三分未中</span>
    <span class="detail__btn one_score" data-type="0">罚球未中</span>
    <br>
    <span class="detail__btn assists" data-type="0">助攻</span>
    <span class="detail__btn assists" data-type="1">三分助攻</span>
    <span class="detail__btn" id="j-lost">失误</span>
    <span class="detail__btn" id="j-rebounds">篮板</span>
    <span class="detail__btn" id="j-steals">抢断</span>
    <span class="detail__btn blocks" data-type="0">盖帽</span>
    <span class="detail__btn blocks" data-type="1">三分盖帽</span>
    <br>
    <span class="detail__btn faul" data-type="0">普通犯规</span>
    <span class="detail__btn faul" data-type="1">犯规罚球</span>
    <span class="detail__btn faul" data-type="2">两分犯规</span>
    <span class="detail__btn faul" data-type="3">三分犯规</span>
    <span class="detail__btn faul" data-type="2">2+1</span>
    <span class="detail__btn faul" data-type="3">3+1</span>
</div>

<div class="modal fade" id="modelAssist">
    <div class="modal-dialog custom-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">选择被助攻球员</h4>
            </div>
            <div id="error" style="display: none;color: red">
                <span class="tc_error"></span>
            </div>
            <div class="modal-body">
                <div class="detail__team1">
                    <form action="" method="get"  style="text-align: left;">
                        <?php foreach ($homePlayers as $key=>$player):?>
                            <div class="detail__team-item">
                                <?php if($playerStatus[$key]['is_playing']==1):?>
                                    <input type="radio" name="doublePlayer" value="<?php echo $key;?>" />
                                     <?php echo $player.' #'.$homeNo[$key];?>
                                <?php endif;?>
                            </div>
                        <?php endforeach;?>
                        <div class="detail__team-item">
                            <input type="button" class="detail__btn" id="j-assists" value="确定" data-dismiss="modal" aria-hidden="true">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

