{load href="/static/css/index/game/detail.css" /}
{load href="/static/css/table.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/echarts/build/dist/echarts.js" /}
{load href="/static/js/index/game/detail.js" /}
<div class="player-data">
    <span class="player-detail">姓名：</span><?php echo $player['name'];?>
    <span class="player-detail">邮箱：</span><?php echo $player['email'];?>
    <span class="player-detail">城市：</span><?php echo $player['city'];?>
    <span class="player-detail">比赛总场数：</span><?php echo $count;?>
    <span class="player-detail">加入队伍数：</span><?php echo $clubNum;?>
</div>
<div class="player-main">
    <div class="data-list">
        <div class="data-two">
            <div class="data-desc">投篮命中率:</div>
            <span class="data-avg2"><?php echo ($avg['three_shoot']+$avg['shoot'])==0?0:number_format(($avg['hit']+$avg['three_hit'])/($avg['shoot']+$avg['three_shoot']),4,'.','')*100;?>%</span>
        </div>
        <div class="data-two">
            <div class="data-desc">三分命中率:</div>
            <span class="data-avg2"><?php echo $avg['three_shoot']==0?0:number_format($avg['three_hit']/$avg['three_shoot'],4,'.','')*100;?>%</span>
        </div>
        <div class="data-two">
            <div class="data-desc">罚篮命中率:</div>
            <span class="data-avg2"><?php echo $avg['penalty_shoot']==0?0:number_format($avg['penalty_hit']/$avg['penalty_shoot'],4,'.','')*100;?>%</span>
        </div>
        <div class="data-two">
            <div class="data-desc">场均上场时间:</div>
            <span class="data-avg"><?php echo number_format($avg['playing_time']/60,1,'.','');?></span>
        </div>
    </div>
    <div class="data-list">
        <div class="data-one">
            <div class="data-desc">场均得分:</div>
            <span class="data-avg"><?php echo $avg['score'];?></span>
        </div>
        <div class="data-one">
            <div class="data-desc">场均篮板:</div>
            <span class="data-avg"><?php echo $avg['rebounds'];?></span>
        </div>
        <div class="data-one">
            <div class="data-desc">场均助攻:</div>
            <span class="data-avg"><?php echo $avg['assists'];?></span>
        </div>
        <div class="data-one">
            <div class="data-desc">场均抢断:</div>
            <span class="data-avg"><?php echo $avg['steals'];?></span>
        </div>
        <div class="data-one">
            <div class="data-desc">场均盖帽:</div>
            <span class="data-avg"><?php echo $avg['blocks'];?></span>
        </div>
    </div>

    <div id="main" style="height:220px"></div>
    <div class="game-data">
        <h3>最近比赛数据统计（场均效率值：<?php echo $per;?>）</h3>
        <table>
            <thead>
            <tr>
                <th>上场时间</th>
                <th>得分</th>
                <th>篮板</th>
                <th>助攻</th>
                <th>投篮</th>
                <th>三分</th>
                <th>罚球</th>
                <th>盖帽</th>
                <th>抢断</th>
                <th>失误</th>
                <th>犯规</th>
            </tr>
            </thead>
            <thead>
            <?php foreach ($datas as $value):?>
                <tr>
                    <td><?php echo number_format($value['playing_time']/60,1,'.','');?></td>
                    <td><?php echo $value['score'];?></td>
                    <td><?php echo $value['rebounds'];?></td>
                    <td><?php echo $value['assists'];?></td>
                    <td><?php echo $value['hit'].'/'.$value['shoot'];?></td>
                    <td><?php echo  $value['three_hit'].'/'.$value['three_shoot'];?></td>
                    <td><?php echo $value['penalty_hit'].'/'.$value['penalty_shoot'];?></td>
                    <td><?php echo $value['blocks'];?></td>
                    <td><?php echo $value['steals'];?></td>
                    <td><?php echo $value['lost'];?></td>
                    <td><?php echo $value['foul'];?></td>
                </tr>
            <?php endforeach;?>
            </thead>
        </table>
    </div>
</div>
<input type="hidden" id="playerId" value="<?php echo $playerId;?>">