{load href="/static/css/user/game/index.css" /}
{load href="/static/css/table.css" /}
{load href="/static/js/jq.js" /}
{load href="/static/js/index/game/player.js" /}
<style>
    .players-data{
        width: 960px;
        margin:20px auto;
        text-align: center;
    }
</style>
<div class="header__info">
    <div class="header__team-name home-name"><?php echo $home['name'];?></div>
    <div class="header__team-score home-score"><span id="homeScore"><?php echo $schedule['home_score'];?></span></div>
    <div class="header__time-box fl">
        <div class="header__picth"><span id="section"><?php echo $schedule['section']>4?'第'.($schedule['section']-4).'加时':'第'.$schedule['section'].'节'?></span></div>
        <div class="header__time"><span id="second"><?php echo (int)($schedule['second']/60);?>:<?php echo str_pad($schedule['second']%60,2,0);?></span></div>
    </div>
    <div class="header__team-name away-name"><?php echo $visiting['name'];?></div>
    <div class="header__team-score away-score"><span id="visitingScore"><?php echo $schedule['visiting_score'];?></span></div>
</div>
<div class="players-data" >
    <h3><?php echo $home['name'];?></h3>
    <table>
        <thead>
            <tr>
                <th>姓名</th>
                <th>得分</th>
                <th>篮板</th>
                <th>助攻</th>
                <th>投篮</th>
                <th>三分</th>
                <th>罚球</th>
                <th>盖帽</th>
                <th>抢断</th>
                <th>失误</th>
                <th>犯规</th>
                <th>上场时间</th>
            </tr>
        </thead>
        <thead class="home-player">
        <?php foreach ($homeData as $value):?>
            <tr>
                <td>
                    <?php echo $value['is_playing']==1?'√':''?>
                    <?php echo idOfFiler('user',['Id'=>$value['user_id']]);?>
                </td>
                <td><?php echo $value['score'];?></td>
                <td><?php echo $value['rebounds'];?></td>
                <td><?php echo $value['assists'];?></td>
                <td><?php echo $value['hit'].'/'.$value['shoot'];?></td>
                <td><?php echo  $value['three_hit'].'/'.$value['three_shoot'];?></td>
                <td><?php echo $value['penalty_hit'].'/'.$value['penalty_shoot'];?></td>
                <td><?php echo $value['blocks'];?></td>
                <td><?php echo $value['steals'];?></td>
                <td><?php echo $value['lost'];?></td>
                <td><?php echo $value['foul'];?></td>
                <td><?php echo number_format($value['playing_time']/60,1,'.','');?></td>
            </tr>
        <?php endforeach;?>
        </thead>
    </table>
    <h3><?php echo $visiting['name'];?></h3>
    <table>
        <thead>
        <tr>
            <th>姓名</th>
            <th>得分</th>
            <th>篮板</th>
            <th>助攻</th>
            <th>投篮</th>
            <th>三分</th>
            <th>罚球</th>
            <th>盖帽</th>
            <th>抢断</th>
            <th>失误</th>
            <th>犯规</th>
            <th>上场时间</th>
        </tr>
        </thead>
        <thead class="visiting-player">
        <?php foreach ($visitingData as $value):?>
            <tr>
                <td>
                    <?php echo $value['is_playing']==1?'√':''?>
                    <?php echo idOfFiler('user',['Id'=>$value['user_id']]);?>
                </td>
                <td><?php echo $value['score'];?></td>
                <td><?php echo $value['rebounds'];?></td>
                <td><?php echo $value['assists'];?></td>
                <td><?php echo $value['hit'].'/'.$value['shoot'];?></td>
                <td><?php echo  $value['three_hit'].'/'.$value['three_shoot'];?></td>
                <td><?php echo $value['penalty_hit'].'/'.$value['penalty_shoot'];?></td>
                <td><?php echo $value['blocks'];?></td>
                <td><?php echo $value['steals'];?></td>
                <td><?php echo $value['lost'];?></td>
                <td><?php echo $value['foul'];?></td>
                <td><?php echo number_format($value['playing_time']/60,1,'.','');?></td>
            </tr>
        <?php endforeach;?>
        </thead>
    </table>
</div>
<input id="scheduleId" type="hidden" value="<?php echo $schedule['Id'];?>">
