<?php
/**
 * Created by PhpStorm.
 * User: Viter
 * Date: 2018/3/4
 * Time: 15:16
 */
namespace app\user\controller;
//use think\Controller;
use base\Base;
use ku\Verify;
use think\Cache;
use think\Session;
use think\Db;
class Login extends Base{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->engine->layout(false);//不使用模板
    }

    public function index(){
        $user = Session::get('user');
        if(isset($user[0]))
            $this->redirect('/');
        return $this->fetch();
    }
    //登陆执行
    public function i(){
        $request = $this->request;
        $email = $request->param('email','','string');
        $password = $request->param('password','','string');
        $captcha = $request->param('captcha','','string');
        $virefyCode = Session::get('login_virefy_code');
        if(strcasecmp($captcha,$virefyCode)!==0){
            return $this->returnJson('验证码不正确');
        }
        if(!Verify::isEmail($email)){
            return $this->returnJson('邮箱格式不正确');
        }
        $user = Db::name('user')->where(array('email'=>$email))->find();
        if(empty($user)){
            return $this->returnJson('用户不存在');
        }
        $encryption = sha1($password.substr($email,0,4));
        if(strcmp($encryption,$user['password'])!==0){
            return $this->returnJson('密码不正确');
        }
        if($user['ban'] !==0){
            return $this->returnJson('账户被禁用');
        }
        Session::push('user',$user);
        return $this->returnJson('登陆成功',true,1);
    }

}